# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

from relationalai.semantics import Date, DateTime, Decimal, Integer, Model, String, avg

m = Model("model")

NrFeet = m.Concept("NrFeet", extends=[Decimal])
RunwayLength = m.Concept("RunwayLength", extends=[NrFeet])
NrPounds = m.Concept("NrPounds", extends=[Integer])
Capacity = m.Concept("Capacity", extends=[NrPounds])
NrMiles = m.Concept("NrMiles", extends=[Decimal])
Distance = m.Concept("Distance", extends=[NrMiles])
NrMinutes = m.Concept("NrMinutes", extends=[Decimal])
Delay = m.Concept("Delay", extends=[NrMinutes])
CancelationCode = m.Concept("CancelationCode", extends=[String])
DegreesLatitude = m.Concept("DegreesLatitude", extends=[Decimal])
DegreesLongitude = m.Concept("DegreesLongitude", extends=[Decimal])
Polygon = m.Concept("Polygon", extends=[String])
RunwayGeometry = m.Concept("RunwayGeometry", extends=[Polygon])
CityName = m.Concept("CityName", extends=[String])
DistanceGroup = m.Concept("DistanceGroup", extends=[Integer])
RunwayDesignator = m.Concept("RunwayDesignator", extends=[String])
SerialNr = m.Concept("SerialNr", extends=[String])
StateCode = m.Concept("StateCode", extends=[String])
StateName = m.Concept("StateName", extends=[String])
TailNr = m.Concept("TailNr", extends=[String])
Year = m.Concept("Year", extends=[String])
CancelationReason = m.Concept("CancelationReason")
State = m.Concept("State")
City = m.Concept("City")
Runway = m.Concept("Runway")
Airport = m.Concept("Airport")
AirportCode = m.Concept("AirportCode", extends=[String])
ManufacturerName = m.Concept("ManufacturerName", extends=[String])
Manufacturer = m.Concept("Manufacturer")
ModelName = m.Concept("ModelName", extends=[String])
Model_2 = m.Concept("Model")
Aircraft = m.Concept("Aircraft")
AirportName = m.Concept("AirportName", extends=[String])
AirportId = m.Concept("AirportId", extends=[String])
MarketName = m.Concept("MarketName", extends=[String])
Market = m.Concept("Market")
FlightNr = m.Concept("FlightNr", extends=[String])
FlightId = m.Concept("FlightId", extends=[String])
Flight = m.Concept("Flight")
CarrierCode = m.Concept("CarrierCode", extends=[String])
CarrierName = m.Concept("CarrierName", extends=[String])
Carrier = m.Concept("Carrier")
RouteId = m.Concept("RouteId", extends=[String])
Route = m.Concept("Route")
database_schema_runways = m.Table("DATABASE.SCHEMA.RUNWAYS", schema={'AIRPORT_CODE': String, 'LENGTH': Decimal, 'SHAPE': String, 'DESIGNATOR': String})
database_schema_aircraft = m.Table("DATABASE.SCHEMA.AIRCRAFT", schema={'SERIAL_NR': String, 'NAME': String, 'NR_SEATS': Integer, 'TAIL_NR': String, 'CARRIER_CODE': String, 'MANUFACTURER': String, 'MODEL': String, 'YEAR': String, 'CAPACITY': Integer})
database_schema_airports = m.Table("DATABASE.SCHEMA.AIRPORTS", schema={'STATE_CODE': String, 'MARKET_NM': String, 'LONGITUDE': Decimal, 'OPENED': String, 'STATE_NM': String, 'CITY_NM': String, 'NAME': String, 'CODE': String, 'LATITUDE': Decimal})
database_schema_flights = m.Table("DATABASE.SCHEMA.FLIGHTS", schema={'DEP_DELAY': Decimal, 'AIR_TIME': String, 'NR': String, 'CARRIER_CODE': String, 'DURATION': String, 'SCHEDULED_DEPARTURE': DateTime, 'ARR_DELAY': Decimal, 'CANCELLED': String, 'CANCEL_CODE': String, 'DISTANCE': Decimal, 'ID': String, 'SCHEDULED_ARRIVAL': DateTime, 'WHEELS_ON': String, 'DATE': Date, 'WHEELS_OFF': String, 'SCHEDULED_DURATION': String, 'TAIL_NR': String, 'DEPARTURE': DateTime, 'ROUTE_ID': String, 'DIVERTED': String, 'ARRIVAL': DateTime})
database_schema_carriers = m.Table("DATABASE.SCHEMA.CARRIERS", schema={'CODE': String, 'NAME': String})
database_schema_routes = m.Table("DATABASE.SCHEMA.ROUTES", schema={'ORIG_AIRPORT_CODE': String, 'DEST_AIRPORT_CODE': String, 'DISTANCE': Decimal, 'DIST_GRP': Integer, 'ID': String, 'NAME': String})

CancelationReason.code = m.Property(f"{CancelationReason} is identified by {CancelationCode}")
State.code = m.Property(f"{State} is identified by {StateCode}")
City.name = m.Property(f"{City} has {CityName}")
City.state = m.Property(f"{City} is located in {State}")
Runway.designator = m.Property(f"{Runway} uses {RunwayDesignator}")
Airport.code = m.Property(f"{Airport} has {AirportCode}")
Runway.airport = m.Property(f"{Runway} belongs to {Airport}")
Manufacturer.name = m.Property(f"{Manufacturer} is identified by {ManufacturerName}")
Model_2.name = m.Property(f"{Model_2} has {ModelName}")
Model_2.manufacturer = m.Property(f"{Model_2} is manufactured by {Manufacturer}")
Aircraft.tailnum = m.Property(f"{Aircraft} is identified by {TailNr}")
Market.name = m.Property(f"{Market} is identified by {MarketName}")
Flight.id = m.Property(f"{Flight} is identified by {FlightId}")
Carrier.code = m.Property(f"{Carrier} uses {CarrierCode}")
Route.id = m.Property(f"{Route} is identified by {RouteId}")
CancelationReason.description = m.Property(f"{CancelationReason} has description {String}")
State.name = m.Property(f"{State} has {StateName}")
Runway.length = m.Property(f"{Runway} has {RunwayLength}")
Runway.geometry = m.Property(f"{Runway} has {RunwayGeometry}")
Aircraft.serial_number = m.Property(f"{Aircraft} has {SerialNr}")
Aircraft.name = m.Property(f"{Aircraft} has name {String}")
Aircraft.number_of_seats = m.Property(f"{Aircraft} has {Integer} seats")
Aircraft.model = m.Property(f"{Aircraft} has {Model_2}")
Aircraft.year_manufactured = m.Property(f"{Aircraft} was manufactured in {Year}")
Aircraft.capacity = m.Property(f"{Aircraft} has {Capacity}")
Aircraft.carrier = m.Property(f"{Aircraft} is operated by {Carrier}")
Airport.city = m.Property(f"{Airport} is located in {City}")
Airport.serves = m.Property(f"{Airport} serves {Market}")
Airport.average_departure_delay = m.Property(f"{Airport} has average departure {Delay}")
Airport.longitude = m.Property(f"{Airport} centers at {DegreesLongitude}")
Airport.average_arrival_delay = m.Property(f"{Airport} has average arrival {Delay}")
Airport.name = m.Property(f"{Airport} has {AirportName}")
Airport.latitude = m.Property(f"{Airport} centers at {DegreesLatitude}")
Flight.departure_delay = m.Property(f"{Flight} has departure {Delay}")
Flight.number = m.Property(f"{Flight} has {FlightNr}")
Flight.scheduled_departure = m.Property(f"{Flight} is scheduled to depart at {DateTime}")
Flight.arrival_delay = m.Property(f"{Flight} has arrival {Delay}")
Flight.canceled = m.Relationship(f"{Flight} was canceled")
Flight.canceled_due_to = m.Property(f"{Flight} was canceled due to {CancelationReason}")
Flight.distance = m.Property(f"{Flight} spans actual {Distance}")
Flight.scheduled_arrival = m.Property(f"{Flight} is scheduled to arrive at {DateTime}")
Flight.registers_longitude_series = m.Property(f"{Flight} at {DateTime} registers {DegreesLongitude}")
Flight.registers_latitude_series = m.Property(f"{Flight} at {DateTime} registers {DegreesLatitude}")
Flight.date = m.Property(f"{Flight} is scheduled to depart on {Date}")
Flight.departs_at = m.Property(f"{Flight} departs at {DateTime}")
Flight.diverted = m.Relationship(f"{Flight} was diverted")
Flight.arrives_at = m.Property(f"{Flight} arrives at {DateTime}")
Flight.route = m.Property(f"{Flight} traverses {Route}")
Flight.aircraft = m.Property(f"{Flight} uses {Aircraft}")
Flight.operated_by = m.Property(f"{Flight} is operated by {Carrier}")
Carrier.name = m.Property(f"{Carrier} has {CarrierName}")
Route.average_departure_delay = m.Property(f"{Route} has average departure {Delay}")
Route.average_arrival_delay = m.Property(f"{Route} has average arrival {Delay}")
Route.distance = m.Property(f"{Route} spans {Distance}")
Route.lies_in = m.Property(f"{Route} has {DistanceGroup}")
Route.route_name = m.Property(f"{Route} has name {String}")
Route.destination = m.Property(f"{Route} connects to destination {Airport}")
Route.departure = m.Property(f"{Route} connects to departure {Airport}")

CancelationReason.identify_by(CancelationReason.code)
State.identify_by(State.code)
City.identify_by(City.name)
City.identify_by(City.state)
Runway.identify_by(Runway.designator)
Runway.identify_by(Runway.airport)
Airport.identify_by(Airport.code)
Manufacturer.identify_by(Manufacturer.name)
Model_2.identify_by(Model_2.name)
Model_2.identify_by(Model_2.manufacturer)
Aircraft.identify_by(Aircraft.tailnum)
Market.identify_by(Market.name)
Flight.identify_by(Flight.id)
Carrier.identify_by(Carrier.code)
Route.identify_by(Route.id)
m.where(airport := Airport.lookup(code=database_schema_runways.AIRPORT_CODE)).define(Runway.new(designator=database_schema_runways.DESIGNATOR, airport=airport))
m.where(runway := Runway.to_identity(designator=database_schema_runways.DESIGNATOR, airport=airport, unsafe=True), airport := Airport.lookup(code=database_schema_runways.AIRPORT_CODE)).define(runway.length(RunwayLength(database_schema_runways.LENGTH)))
m.where(runway := Runway.to_identity(designator=database_schema_runways.DESIGNATOR, airport=airport, unsafe=True), airport := Airport.lookup(code=database_schema_runways.AIRPORT_CODE)).define(runway.geometry(RunwayGeometry(database_schema_runways.SHAPE)))
m.define(Manufacturer.new(name=database_schema_aircraft.MANUFACTURER))
m.where(manufacturer := Manufacturer.lookup(name=database_schema_aircraft.MANUFACTURER)).define(Model_2.new(name=database_schema_aircraft.MODEL, manufacturer=manufacturer))
m.define(Aircraft.new(tailnum=database_schema_aircraft.TAIL_NR))
m.where(aircraft := Aircraft.to_identity(tailnum=database_schema_aircraft.TAIL_NR, unsafe=True)).define(aircraft.serial_number(SerialNr(database_schema_aircraft.SERIAL_NR)))
m.where(aircraft := Aircraft.to_identity(tailnum=database_schema_aircraft.TAIL_NR, unsafe=True)).define(aircraft.name(database_schema_aircraft.NAME))
m.where(aircraft := Aircraft.to_identity(tailnum=database_schema_aircraft.TAIL_NR, unsafe=True)).define(aircraft.number_of_seats(database_schema_aircraft.NR_SEATS))
m.where(aircraft := Aircraft.to_identity(tailnum=database_schema_aircraft.TAIL_NR, unsafe=True), manufacturer := Manufacturer.lookup(name=database_schema_aircraft.MANUFACTURER), model := Model_2.lookup(name=database_schema_aircraft.MODEL, manufacturer=manufacturer)).define(aircraft.model(model))
m.where(aircraft := Aircraft.to_identity(tailnum=database_schema_aircraft.TAIL_NR, unsafe=True)).define(aircraft.year_manufactured(Year(database_schema_aircraft.YEAR)))
m.where(aircraft := Aircraft.to_identity(tailnum=database_schema_aircraft.TAIL_NR, unsafe=True)).define(aircraft.capacity(Capacity(database_schema_aircraft.CAPACITY)))
m.where(aircraft := Aircraft.to_identity(tailnum=database_schema_aircraft.TAIL_NR, unsafe=True), carrier := Carrier.lookup(code=database_schema_aircraft.CARRIER_CODE)).define(aircraft.carrier(carrier))
m.define(State.new(code=database_schema_airports.STATE_CODE))
m.where(state := State.to_identity(code=database_schema_airports.STATE_CODE, unsafe=True)).define(state.name(StateName(database_schema_airports.STATE_NM)))
m.where(state := State.lookup(code=database_schema_airports.STATE_CODE)).define(City.new(name=database_schema_airports.CITY_NM, state=state))
m.define(Market.new(name=database_schema_airports.MARKET_NM))
m.define(Airport.new(code=database_schema_airports.CODE))
m.where(airport := Airport.to_identity(code=database_schema_airports.CODE, unsafe=True), state := State.lookup(code=database_schema_airports.STATE_CODE), city := City.lookup(name=database_schema_airports.CITY_NM, state=state)).define(airport.city(city))
m.where(airport := Airport.to_identity(code=database_schema_airports.CODE, unsafe=True), market := Market.lookup(name=database_schema_airports.MARKET_NM)).define(airport.serves(market))
m.where(airport := Airport.to_identity(code=database_schema_airports.CODE, unsafe=True)).define(airport.longitude(DegreesLongitude(database_schema_airports.LONGITUDE)))
m.where(airport := Airport.to_identity(code=database_schema_airports.CODE, unsafe=True)).define(airport.name(AirportName(database_schema_airports.NAME)))
m.where(airport := Airport.to_identity(code=database_schema_airports.CODE, unsafe=True)).define(airport.latitude(DegreesLatitude(database_schema_airports.LATITUDE)))
m.define(Flight.new(id=database_schema_flights.ID))
m.where(database_schema_flights.DIVERTED == True).define(Flight.new(id=database_schema_flights.ID))
m.where(flight := Flight.to_identity(id=database_schema_flights.ID, unsafe=True), database_schema_flights.DIVERTED == True).define(Flight.diverted(flight))
m.where(database_schema_flights.CANCELLED == True).define(Flight.new(id=database_schema_flights.ID))
m.where(flight := Flight.to_identity(id=database_schema_flights.ID, unsafe=True), database_schema_flights.CANCELLED == True).define(Flight.canceled(flight))
m.where(flight := Flight.to_identity(id=database_schema_flights.ID, unsafe=True)).define(flight.arrival_delay(Delay(database_schema_flights.ARR_DELAY)))
m.where(flight := Flight.to_identity(id=database_schema_flights.ID, unsafe=True)).define(flight.departure_delay(Delay(database_schema_flights.DEP_DELAY)))
m.where(flight := Flight.to_identity(id=database_schema_flights.ID, unsafe=True)).define(flight.number(FlightNr(database_schema_flights.NR)))
m.where(flight := Flight.to_identity(id=database_schema_flights.ID, unsafe=True)).define(flight.scheduled_departure(database_schema_flights.SCHEDULED_DEPARTURE))
m.where(flight := Flight.to_identity(id=database_schema_flights.ID, unsafe=True), cancelationreason := CancelationReason.lookup(code=database_schema_flights.CANCEL_CODE)).define(flight.canceled_due_to(cancelationreason))
m.where(flight := Flight.to_identity(id=database_schema_flights.ID, unsafe=True)).define(flight.distance(Distance(database_schema_flights.DISTANCE)))
m.where(flight := Flight.to_identity(id=database_schema_flights.ID, unsafe=True)).define(flight.scheduled_arrival(database_schema_flights.SCHEDULED_ARRIVAL))
m.where(flight := Flight.to_identity(id=database_schema_flights.ID, unsafe=True)).define(flight.date(database_schema_flights.DATE))
m.where(flight := Flight.to_identity(id=database_schema_flights.ID, unsafe=True)).define(flight.departs_at(database_schema_flights.DEPARTURE))
m.where(flight := Flight.to_identity(id=database_schema_flights.ID, unsafe=True)).define(flight.arrives_at(database_schema_flights.ARRIVAL))
m.where(flight := Flight.to_identity(id=database_schema_flights.ID, unsafe=True), route := Route.lookup(id=database_schema_flights.ROUTE_ID)).define(flight.route(route))
m.where(flight := Flight.to_identity(id=database_schema_flights.ID, unsafe=True), aircraft := Aircraft.lookup(tailnum=database_schema_flights.TAIL_NR)).define(flight.aircraft(aircraft))
m.where(flight := Flight.to_identity(id=database_schema_flights.ID, unsafe=True), carrier := Carrier.lookup(code=database_schema_flights.CARRIER_CODE)).define(flight.operated_by(carrier))
m.define(Carrier.new(code=database_schema_carriers.CODE))
m.where(carrier := Carrier.to_identity(code=database_schema_carriers.CODE, unsafe=True)).define(carrier.name(CarrierName(database_schema_carriers.NAME)))
m.define(Route.new(id=database_schema_routes.ID))
m.where(route := Route.to_identity(id=database_schema_routes.ID, unsafe=True)).define(route.distance(Distance(database_schema_routes.DISTANCE)))
m.where(route := Route.to_identity(id=database_schema_routes.ID, unsafe=True)).define(route.lies_in(DistanceGroup(database_schema_routes.DIST_GRP)))
m.where(route := Route.to_identity(id=database_schema_routes.ID, unsafe=True)).define(route.route_name(database_schema_routes.NAME))
m.where(route := Route.to_identity(id=database_schema_routes.ID, unsafe=True), airport := Airport.lookup(code=database_schema_routes.DEST_AIRPORT_CODE)).define(route.destination(airport))
m.where(route := Route.to_identity(id=database_schema_routes.ID, unsafe=True), airport := Airport.lookup(code=database_schema_routes.ORIG_AIRPORT_CODE)).define(route.departure(airport))
m.where(delay := Delay.ref(), Airport, delay == avg(Flight.departure_delay).per(Airport).where(Airport == Flight.route.departure)).define(Airport.average_departure_delay(delay))
m.where(delay := Delay.ref(), Airport, delay == avg(Flight.arrival_delay).per(Airport).where(Airport == Flight.route.destination)).define(Airport.average_arrival_delay(delay))
m.where(delay := Delay.ref(), Route, delay == avg(Flight.departure_delay).per(Route).where(Flight.route(Route))).define(Route.average_departure_delay(delay))
m.where(delay := Delay.ref(), Route, delay == avg(Flight.arrival_delay).per(Route).where(Flight.route(Route))).define(Route.average_arrival_delay(delay))
