# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

from relationalai.semantics import Date, Decimal, Integer, Model, String

m = Model("model")

Region = m.Concept("Region")
Nation = m.Concept("Nation")
Supplier = m.Concept("Supplier")
Part = m.Concept("Part")
PartSupplier = m.Concept("PartSupplier")
CustOrder = m.Concept("CustOrder")
OrderLineitem = m.Concept("OrderLineitem")
Customer = m.Concept("Customer")
kse_tpch_sf1_customer = m.Table("KSE.TPCH_SF1.CUSTOMER", schema={'C_CUSTKEY': Integer, 'C_NAME': String, 'C_ADDRESS': String, 'C_NATIONKEY': Integer, 'C_PHONE': String, 'C_ACCTBAL': Decimal, 'C_MKTSEGMENT': String, 'C_COMMENT': String})
kse_tpch_sf1_orders = m.Table("KSE.TPCH_SF1.ORDERS", schema={'O_ORDERKEY': Integer, 'O_CUSTKEY': Integer, 'O_ORDERSTATUS': String, 'O_TOTALPRICE': Decimal, 'O_ORDERDATE': Date, 'O_ORDERPRIORITY': String, 'O_CLERK': String, 'O_SHIPPRIORITY': Decimal, 'O_COMMENT': String})
kse_tpch_sf1_lineitem = m.Table("KSE.TPCH_SF1.LINEITEM", schema={'L_ORDERKEY': Integer, 'L_PARTKEY': Integer, 'L_SUPPKEY': Integer, 'L_LINENUMBER': Integer, 'L_QUANTITY': Decimal, 'L_EXTENDEDPRICE': Decimal, 'L_DISCOUNT': Decimal, 'L_TAX': Decimal, 'L_RETURNFLAG': String, 'L_LINESTATUS': String, 'L_SHIPDATE': Date, 'L_COMMITDATE': Date, 'L_RECEIPTDATE': Date, 'L_SHIPINSTRUCT': String, 'L_SHIPMODE': String, 'L_COMMENT': String})
kse_tpch_sf1_partsupp = m.Table("KSE.TPCH_SF1.PARTSUPP", schema={'PS_PARTKEY': Integer, 'PS_SUPPKEY': Integer, 'PS_AVAILQTY': Decimal, 'PS_SUPPLYCOST': Decimal, 'PS_COMMENT': String})
kse_tpch_sf1_part = m.Table("KSE.TPCH_SF1.PART", schema={'P_PARTKEY': Integer, 'P_NAME': String, 'P_MFGR': String, 'P_BRAND': String, 'P_TYPE': String, 'P_SIZE': Integer, 'P_CONTAINER': String, 'P_RETAILPRICE': Decimal, 'P_COMMENT': String})
kse_tpch_sf1_supplier = m.Table("KSE.TPCH_SF1.SUPPLIER", schema={'S_SUPPKEY': Integer, 'S_NAME': String, 'S_ADDRESS': String, 'S_NATIONKEY': Integer, 'S_PHONE': String, 'S_ACCTBAL': Decimal, 'S_COMMENT': String})
kse_tpch_sf1_nation = m.Table("KSE.TPCH_SF1.NATION", schema={'N_NATIONKEY': Integer, 'N_NAME': String, 'N_REGIONKEY': Integer, 'N_COMMENT': String})
kse_tpch_sf1_region = m.Table("KSE.TPCH_SF1.REGION", schema={'R_REGIONKEY': Integer, 'R_NAME': String, 'R_COMMENT': String})

Region.region_key = m.Property(f"{Region} is identified by {Integer}")
Nation.nation_key = m.Property(f"{Nation} is identified by {Integer}")
Supplier.supplier_key = m.Property(f"{Supplier} is identified by {Integer}")
Part.part_key = m.Property(f"{Part} is identified by {Integer}")
PartSupplier.part_key = m.Property(f"{PartSupplier} is identified by part {Integer}")
PartSupplier.supplier_key = m.Property(f"{PartSupplier} is identified by supplier {Integer}")
CustOrder.order_key = m.Property(f"{CustOrder} is identified by {Integer}")
OrderLineitem.order_key = m.Property(f"{OrderLineitem} is identified by order {Integer}")
OrderLineitem.order_lineitem_number = m.Property(f"{OrderLineitem} is identified by line {Integer}")
Customer.customer_key = m.Property(f"{Customer} is identified by {Integer}")
Region.region_comment = m.Property(f"{Region} has {String:region_comment}")
Region.region_name = m.Property(f"{Region} has {String:region_name}")
Nation.nation_comment = m.Property(f"{Nation} has {String:nation_comment}")
Nation.region_key = m.Property(f"{Nation} has {Integer:region_key}")
Nation.nation_name = m.Property(f"{Nation} has {String:nation_name}")
Nation.North_America = m.Relationship(f"{Nation} has North America filter")
Nation.nations_to_regions = m.Property(f"{Nation} maps to {Region}")
Supplier.supplier_address = m.Property(f"{Supplier} has {String:supplier_address}")
Supplier.supplier_phone = m.Property(f"{Supplier} has {String:supplier_phone}")
Supplier.supplier_account_balance = m.Property(f"{Supplier} has {Decimal:supplier_account_balance}")
Supplier.supplier_comment = m.Property(f"{Supplier} has {String:supplier_comment}")
Supplier.supplier_name = m.Property(f"{Supplier} has {String:supplier_name}")
Supplier.nation_key = m.Property(f"{Supplier} has {Integer:nation_key}")
Supplier.suppliers_to_nations = m.Property(f"{Supplier} maps to {Nation}")
Part.part_retail_price = m.Property(f"{Part} has {Decimal:part_retail_price}")
Part.part_comment = m.Property(f"{Part} has {String:part_comment}")
Part.part_name = m.Property(f"{Part} has {String:part_name}")
Part.part_manufacturer_name = m.Property(f"{Part} has {String:part_manufacturer_name}")
Part.part_brand = m.Property(f"{Part} has {String:part_brand}")
Part.part_type = m.Property(f"{Part} has {String:part_type}")
Part.part_container = m.Property(f"{Part} has {String:part_container}")
Part.part_size = m.Property(f"{Part} has {Integer:part_size}")
PartSupplier.available_quantity = m.Property(f"{PartSupplier} has {Decimal:available_quantity}")
PartSupplier.part_supplier_supply_cost = m.Property(f"{PartSupplier} has {Decimal:part_supplier_supply_cost}")
PartSupplier.part_supplier_comment = m.Property(f"{PartSupplier} has {String:part_supplier_comment}")
PartSupplier.part_suppliers_to_part = m.Property(f"{PartSupplier} maps to {Part}")
PartSupplier.part_suppliers_to_supplier = m.Property(f"{PartSupplier} maps to {Supplier}")
CustOrder.order_gross_total = m.Property(f"{CustOrder} has {Decimal:order_gross_total}")
CustOrder.order_clerk = m.Property(f"{CustOrder} has {String:order_clerk}")
CustOrder.order_ship_priority = m.Property(f"{CustOrder} has {Decimal:order_ship_priority}")
CustOrder.order_comment = m.Property(f"{CustOrder} has {String:order_comment}")
CustOrder.customer_key = m.Property(f"{CustOrder} has {Integer:customer_key}")
CustOrder.order_status = m.Property(f"{CustOrder} has {String:order_status}")
CustOrder.order_priority = m.Property(f"{CustOrder} has {String:order_priority}")
CustOrder.order_date = m.Property(f"{CustOrder} has {Date:order_date}")
CustOrder.Yesterday = m.Relationship(f"{CustOrder} has Yesterday filter")
CustOrder.YTD = m.Relationship(f"{CustOrder} has YTD filter")
CustOrder.orders_to_customers = m.Property(f"{CustOrder} maps to {Customer}")
OrderLineitem.lineitem_quantity = m.Property(f"{OrderLineitem} has {Decimal:lineitem_quantity}")
OrderLineitem.lineitem_extended_price = m.Property(f"{OrderLineitem} has {Decimal:lineitem_extended_price}")
OrderLineitem.lineitem_discount = m.Property(f"{OrderLineitem} has {Decimal:lineitem_discount}")
OrderLineitem.lineitem_tax = m.Property(f"{OrderLineitem} has {Decimal:lineitem_tax}")
OrderLineitem.lineitem_comment = m.Property(f"{OrderLineitem} has {String:lineitem_comment}")
OrderLineitem.net_revenue = m.Property(f"{OrderLineitem} has {Decimal:net_revenue}")
OrderLineitem.gross_revenue = m.Property(f"{OrderLineitem} has {Decimal:gross_revenue}")
OrderLineitem.part_key = m.Property(f"{OrderLineitem} has {Integer:part_key}")
OrderLineitem.supplier_key = m.Property(f"{OrderLineitem} has {Integer:supplier_key}")
OrderLineitem.lineitem_return_flag = m.Property(f"{OrderLineitem} has {String:lineitem_return_flag}")
OrderLineitem.lineitem_status = m.Property(f"{OrderLineitem} has {String:lineitem_status}")
OrderLineitem.lineitem_shipping_instructions = m.Property(f"{OrderLineitem} has {String:lineitem_shipping_instructions}")
OrderLineitem.lineitem_shipping_mode = m.Property(f"{OrderLineitem} has {String:lineitem_shipping_mode}")
OrderLineitem.lineitem_ship_date = m.Property(f"{OrderLineitem} has {Date:lineitem_ship_date}")
OrderLineitem.lineitem_commit_date = m.Property(f"{OrderLineitem} has {Date:lineitem_commit_date}")
OrderLineitem.lineitem_receipt_date = m.Property(f"{OrderLineitem} has {Date:lineitem_receipt_date}")
OrderLineitem.lineitems_to_orders = m.Property(f"{OrderLineitem} maps to {CustOrder}")
OrderLineitem.order_lineitems_to_part_suppliers = m.Property(f"{OrderLineitem} maps to {PartSupplier}")
Customer.customer_address = m.Property(f"{Customer} has {String:customer_address}")
Customer.customer_phone = m.Property(f"{Customer} has {String:customer_phone}")
Customer.customer_account_balance = m.Property(f"{Customer} has {Decimal:customer_account_balance}")
Customer.customer_comment = m.Property(f"{Customer} has {String:customer_comment}")
Customer.nation_key = m.Property(f"{Customer} has {Integer:nation_key}")
Customer.customer_name = m.Property(f"{Customer} has {String:customer_name}")
Customer.customer_market_segment = m.Property(f"{Customer} has {String:customer_market_segment}")
Customer.automobile_market_segment = m.Relationship(f"{Customer} has automobile_market_segment filter")
Customer.top_10_customers_by_higest_account_balance = m.Relationship(f"{Customer} has top_10_customers_by_higest_account_balance filter")
Customer.customers_to_nations = m.Property(f"{Customer} maps to {Nation}")

Region.identify_by(Region.region_key)
Nation.identify_by(Nation.nation_key)
Supplier.identify_by(Supplier.supplier_key)
Part.identify_by(Part.part_key)
PartSupplier.identify_by(PartSupplier.part_key)
PartSupplier.identify_by(PartSupplier.supplier_key)
CustOrder.identify_by(CustOrder.order_key)
OrderLineitem.identify_by(OrderLineitem.order_key)
OrderLineitem.identify_by(OrderLineitem.order_lineitem_number)
Customer.identify_by(Customer.customer_key)
m.define(Region.new(region_key=kse_tpch_sf1_region.R_REGIONKEY))
m.where(region := Region.to_identity(region_key=kse_tpch_sf1_region.R_REGIONKEY, unsafe=True)).define(region.region_name(kse_tpch_sf1_region.R_NAME))
m.where(region := Region.to_identity(region_key=kse_tpch_sf1_region.R_REGIONKEY, unsafe=True)).define(region.region_comment(kse_tpch_sf1_region.R_COMMENT))
m.define(Nation.new(nation_key=kse_tpch_sf1_nation.N_NATIONKEY))
m.where(nation := Nation.to_identity(nation_key=kse_tpch_sf1_nation.N_NATIONKEY, unsafe=True)).define(nation.nation_name(kse_tpch_sf1_nation.N_NAME))
m.where(nation := Nation.to_identity(nation_key=kse_tpch_sf1_nation.N_NATIONKEY, unsafe=True)).define(nation.nation_comment(kse_tpch_sf1_nation.N_COMMENT))
m.where(nation := Nation.to_identity(nation_key=kse_tpch_sf1_nation.N_NATIONKEY, unsafe=True)).define(nation.region_key(kse_tpch_sf1_nation.N_REGIONKEY))
m.define(Supplier.new(supplier_key=kse_tpch_sf1_supplier.S_SUPPKEY))
m.where(supplier := Supplier.to_identity(supplier_key=kse_tpch_sf1_supplier.S_SUPPKEY, unsafe=True)).define(supplier.supplier_name(kse_tpch_sf1_supplier.S_NAME))
m.where(supplier := Supplier.to_identity(supplier_key=kse_tpch_sf1_supplier.S_SUPPKEY, unsafe=True)).define(supplier.supplier_address(kse_tpch_sf1_supplier.S_ADDRESS))
m.where(supplier := Supplier.to_identity(supplier_key=kse_tpch_sf1_supplier.S_SUPPKEY, unsafe=True)).define(supplier.supplier_phone(kse_tpch_sf1_supplier.S_PHONE))
m.where(supplier := Supplier.to_identity(supplier_key=kse_tpch_sf1_supplier.S_SUPPKEY, unsafe=True)).define(supplier.supplier_account_balance(kse_tpch_sf1_supplier.S_ACCTBAL))
m.where(supplier := Supplier.to_identity(supplier_key=kse_tpch_sf1_supplier.S_SUPPKEY, unsafe=True)).define(supplier.supplier_comment(kse_tpch_sf1_supplier.S_COMMENT))
m.where(supplier := Supplier.to_identity(supplier_key=kse_tpch_sf1_supplier.S_SUPPKEY, unsafe=True)).define(supplier.nation_key(kse_tpch_sf1_supplier.S_NATIONKEY))
m.define(Part.new(part_key=kse_tpch_sf1_part.P_PARTKEY))
m.where(part := Part.to_identity(part_key=kse_tpch_sf1_part.P_PARTKEY, unsafe=True)).define(part.part_name(kse_tpch_sf1_part.P_NAME))
m.where(part := Part.to_identity(part_key=kse_tpch_sf1_part.P_PARTKEY, unsafe=True)).define(part.part_manufacturer_name(kse_tpch_sf1_part.P_MFGR))
m.where(part := Part.to_identity(part_key=kse_tpch_sf1_part.P_PARTKEY, unsafe=True)).define(part.part_brand(kse_tpch_sf1_part.P_BRAND))
m.where(part := Part.to_identity(part_key=kse_tpch_sf1_part.P_PARTKEY, unsafe=True)).define(part.part_type(kse_tpch_sf1_part.P_TYPE))
m.where(part := Part.to_identity(part_key=kse_tpch_sf1_part.P_PARTKEY, unsafe=True)).define(part.part_size(kse_tpch_sf1_part.P_SIZE))
m.where(part := Part.to_identity(part_key=kse_tpch_sf1_part.P_PARTKEY, unsafe=True)).define(part.part_container(kse_tpch_sf1_part.P_CONTAINER))
m.where(part := Part.to_identity(part_key=kse_tpch_sf1_part.P_PARTKEY, unsafe=True)).define(part.part_retail_price(kse_tpch_sf1_part.P_RETAILPRICE))
m.where(part := Part.to_identity(part_key=kse_tpch_sf1_part.P_PARTKEY, unsafe=True)).define(part.part_comment(kse_tpch_sf1_part.P_COMMENT))
m.define(PartSupplier.new(part_key=kse_tpch_sf1_partsupp.PS_PARTKEY, supplier_key=kse_tpch_sf1_partsupp.PS_SUPPKEY))
m.where(partsupplier := PartSupplier.to_identity(part_key=kse_tpch_sf1_partsupp.PS_PARTKEY, supplier_key=kse_tpch_sf1_partsupp.PS_SUPPKEY, unsafe=True)).define(partsupplier.available_quantity(kse_tpch_sf1_partsupp.PS_AVAILQTY))
m.where(partsupplier := PartSupplier.to_identity(part_key=kse_tpch_sf1_partsupp.PS_PARTKEY, supplier_key=kse_tpch_sf1_partsupp.PS_SUPPKEY, unsafe=True)).define(partsupplier.part_supplier_supply_cost(kse_tpch_sf1_partsupp.PS_SUPPLYCOST))
m.where(partsupplier := PartSupplier.to_identity(part_key=kse_tpch_sf1_partsupp.PS_PARTKEY, supplier_key=kse_tpch_sf1_partsupp.PS_SUPPKEY, unsafe=True)).define(partsupplier.part_supplier_comment(kse_tpch_sf1_partsupp.PS_COMMENT))
m.define(CustOrder.new(order_key=kse_tpch_sf1_orders.O_ORDERKEY))
m.where(custorder := CustOrder.to_identity(order_key=kse_tpch_sf1_orders.O_ORDERKEY, unsafe=True)).define(custorder.order_gross_total(kse_tpch_sf1_orders.O_TOTALPRICE))
m.where(custorder := CustOrder.to_identity(order_key=kse_tpch_sf1_orders.O_ORDERKEY, unsafe=True)).define(custorder.order_clerk(kse_tpch_sf1_orders.O_CLERK))
m.where(custorder := CustOrder.to_identity(order_key=kse_tpch_sf1_orders.O_ORDERKEY, unsafe=True)).define(custorder.order_ship_priority(kse_tpch_sf1_orders.O_SHIPPRIORITY))
m.where(custorder := CustOrder.to_identity(order_key=kse_tpch_sf1_orders.O_ORDERKEY, unsafe=True)).define(custorder.order_comment(kse_tpch_sf1_orders.O_COMMENT))
m.where(custorder := CustOrder.to_identity(order_key=kse_tpch_sf1_orders.O_ORDERKEY, unsafe=True)).define(custorder.customer_key(kse_tpch_sf1_orders.O_CUSTKEY))
m.where(custorder := CustOrder.to_identity(order_key=kse_tpch_sf1_orders.O_ORDERKEY, unsafe=True)).define(custorder.order_status(kse_tpch_sf1_orders.O_ORDERSTATUS))
m.where(custorder := CustOrder.to_identity(order_key=kse_tpch_sf1_orders.O_ORDERKEY, unsafe=True)).define(custorder.order_priority(kse_tpch_sf1_orders.O_ORDERPRIORITY))
m.where(custorder := CustOrder.to_identity(order_key=kse_tpch_sf1_orders.O_ORDERKEY, unsafe=True)).define(custorder.order_date(kse_tpch_sf1_orders.O_ORDERDATE))
m.define(OrderLineitem.new(order_key=kse_tpch_sf1_lineitem.L_ORDERKEY, order_lineitem_number=kse_tpch_sf1_lineitem.L_LINENUMBER))
m.where(orderlineitem := OrderLineitem.to_identity(order_key=kse_tpch_sf1_lineitem.L_ORDERKEY, order_lineitem_number=kse_tpch_sf1_lineitem.L_LINENUMBER, unsafe=True)).define(orderlineitem.lineitem_quantity(kse_tpch_sf1_lineitem.L_QUANTITY))
m.where(orderlineitem := OrderLineitem.to_identity(order_key=kse_tpch_sf1_lineitem.L_ORDERKEY, order_lineitem_number=kse_tpch_sf1_lineitem.L_LINENUMBER, unsafe=True)).define(orderlineitem.lineitem_extended_price(kse_tpch_sf1_lineitem.L_EXTENDEDPRICE))
m.where(orderlineitem := OrderLineitem.to_identity(order_key=kse_tpch_sf1_lineitem.L_ORDERKEY, order_lineitem_number=kse_tpch_sf1_lineitem.L_LINENUMBER, unsafe=True)).define(orderlineitem.lineitem_discount(kse_tpch_sf1_lineitem.L_DISCOUNT))
m.where(orderlineitem := OrderLineitem.to_identity(order_key=kse_tpch_sf1_lineitem.L_ORDERKEY, order_lineitem_number=kse_tpch_sf1_lineitem.L_LINENUMBER, unsafe=True)).define(orderlineitem.lineitem_tax(kse_tpch_sf1_lineitem.L_TAX))
m.where(orderlineitem := OrderLineitem.to_identity(order_key=kse_tpch_sf1_lineitem.L_ORDERKEY, order_lineitem_number=kse_tpch_sf1_lineitem.L_LINENUMBER, unsafe=True)).define(orderlineitem.lineitem_comment(kse_tpch_sf1_lineitem.L_COMMENT))
m.where(orderlineitem := OrderLineitem.to_identity(order_key=kse_tpch_sf1_lineitem.L_ORDERKEY, order_lineitem_number=kse_tpch_sf1_lineitem.L_LINENUMBER, unsafe=True)).define(orderlineitem.part_key(kse_tpch_sf1_lineitem.L_PARTKEY))
m.where(orderlineitem := OrderLineitem.to_identity(order_key=kse_tpch_sf1_lineitem.L_ORDERKEY, order_lineitem_number=kse_tpch_sf1_lineitem.L_LINENUMBER, unsafe=True)).define(orderlineitem.supplier_key(kse_tpch_sf1_lineitem.L_SUPPKEY))
m.where(orderlineitem := OrderLineitem.to_identity(order_key=kse_tpch_sf1_lineitem.L_ORDERKEY, order_lineitem_number=kse_tpch_sf1_lineitem.L_LINENUMBER, unsafe=True)).define(orderlineitem.lineitem_return_flag(kse_tpch_sf1_lineitem.L_RETURNFLAG))
m.where(orderlineitem := OrderLineitem.to_identity(order_key=kse_tpch_sf1_lineitem.L_ORDERKEY, order_lineitem_number=kse_tpch_sf1_lineitem.L_LINENUMBER, unsafe=True)).define(orderlineitem.lineitem_status(kse_tpch_sf1_lineitem.L_LINESTATUS))
m.where(orderlineitem := OrderLineitem.to_identity(order_key=kse_tpch_sf1_lineitem.L_ORDERKEY, order_lineitem_number=kse_tpch_sf1_lineitem.L_LINENUMBER, unsafe=True)).define(orderlineitem.lineitem_shipping_instructions(kse_tpch_sf1_lineitem.L_SHIPINSTRUCT))
m.where(orderlineitem := OrderLineitem.to_identity(order_key=kse_tpch_sf1_lineitem.L_ORDERKEY, order_lineitem_number=kse_tpch_sf1_lineitem.L_LINENUMBER, unsafe=True)).define(orderlineitem.lineitem_shipping_mode(kse_tpch_sf1_lineitem.L_SHIPMODE))
m.where(orderlineitem := OrderLineitem.to_identity(order_key=kse_tpch_sf1_lineitem.L_ORDERKEY, order_lineitem_number=kse_tpch_sf1_lineitem.L_LINENUMBER, unsafe=True)).define(orderlineitem.lineitem_ship_date(kse_tpch_sf1_lineitem.L_SHIPDATE))
m.where(orderlineitem := OrderLineitem.to_identity(order_key=kse_tpch_sf1_lineitem.L_ORDERKEY, order_lineitem_number=kse_tpch_sf1_lineitem.L_LINENUMBER, unsafe=True)).define(orderlineitem.lineitem_commit_date(kse_tpch_sf1_lineitem.L_COMMITDATE))
m.where(orderlineitem := OrderLineitem.to_identity(order_key=kse_tpch_sf1_lineitem.L_ORDERKEY, order_lineitem_number=kse_tpch_sf1_lineitem.L_LINENUMBER, unsafe=True)).define(orderlineitem.lineitem_receipt_date(kse_tpch_sf1_lineitem.L_RECEIPTDATE))
m.define(Customer.new(customer_key=kse_tpch_sf1_customer.C_CUSTKEY))
m.where(customer := Customer.to_identity(customer_key=kse_tpch_sf1_customer.C_CUSTKEY, unsafe=True)).define(customer.customer_name(kse_tpch_sf1_customer.C_NAME))
m.where(customer := Customer.to_identity(customer_key=kse_tpch_sf1_customer.C_CUSTKEY, unsafe=True)).define(customer.customer_address(kse_tpch_sf1_customer.C_ADDRESS))
m.where(customer := Customer.to_identity(customer_key=kse_tpch_sf1_customer.C_CUSTKEY, unsafe=True)).define(customer.customer_phone(kse_tpch_sf1_customer.C_PHONE))
m.where(customer := Customer.to_identity(customer_key=kse_tpch_sf1_customer.C_CUSTKEY, unsafe=True)).define(customer.customer_account_balance(kse_tpch_sf1_customer.C_ACCTBAL))
m.where(customer := Customer.to_identity(customer_key=kse_tpch_sf1_customer.C_CUSTKEY, unsafe=True)).define(customer.customer_market_segment(kse_tpch_sf1_customer.C_MKTSEGMENT))
m.where(customer := Customer.to_identity(customer_key=kse_tpch_sf1_customer.C_CUSTKEY, unsafe=True)).define(customer.customer_comment(kse_tpch_sf1_customer.C_COMMENT))
m.where(customer := Customer.to_identity(customer_key=kse_tpch_sf1_customer.C_CUSTKEY, unsafe=True)).define(customer.nation_key(kse_tpch_sf1_customer.C_NATIONKEY))
m.where(Nation, Region, Nation.region_key == Region.region_key).define(Nation.nations_to_regions(Region))
m.where(Supplier, Nation, Supplier.nation_key == Nation.nation_key).define(Supplier.suppliers_to_nations(Nation))
m.where(PartSupplier, Part, PartSupplier.part_key == Part.part_key).define(PartSupplier.part_suppliers_to_part(Part))
m.where(PartSupplier, Supplier, PartSupplier.supplier_key == Supplier.supplier_key).define(PartSupplier.part_suppliers_to_supplier(Supplier))
m.where(CustOrder, Customer, CustOrder.customer_key == Customer.customer_key).define(CustOrder.orders_to_customers(Customer))
m.where(OrderLineitem, CustOrder, OrderLineitem.order_key == CustOrder.order_key).define(OrderLineitem.lineitems_to_orders(CustOrder))
m.where(OrderLineitem, PartSupplier, OrderLineitem.part_key == PartSupplier.part_key, OrderLineitem.supplier_key == PartSupplier.supplier_key).define(OrderLineitem.order_lineitems_to_part_suppliers(PartSupplier))
m.where(Customer, Nation, Customer.nation_key == Nation.nation_key).define(Customer.customers_to_nations(Nation))
