#!/usr/bin/env python3
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements. See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

"""Publish executable schemas and an endpoint capture from the profile examples."""

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PROFILE = ROOT / "docs/proposals/execute-query-mcp.md"
DESTINATION = ROOT / "validation/mcp"
LICENSE = (
    "Licensed to the Apache Software Foundation (ASF) under one or more "
    "contributor license agreements. See NOTICE for copyright ownership. "
    "Licensed under the Apache License, Version 2.0; "
    "http://www.apache.org/licenses/LICENSE-2.0 . "
    "Unless required by applicable law or agreed to in writing, distributed "
    "on an AS IS BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND."
)


def generated_files() -> dict[str, str]:
    blocks = [
        json.loads(block)
        for block in re.findall(r"```json\n(.*?)\n```", PROFILE.read_text(encoding="utf-8"), re.S)
    ]
    schemas = [block for block in blocks if "$schema" in block]
    if len(schemas) != 2:
        raise ValueError("Expected exactly the input and output schemas in the profile")
    inputs, outputs = schemas
    for name in ("expression", "projection", "predicate", "query"):
        if inputs["$defs"][name] != outputs["$defs"][name]:
            raise ValueError(f"Request and replacement query definitions differ: {name}")
    version = outputs["properties"]["contract_version"]["const"]
    query = {
        "$schema": inputs["$schema"],
        "$ref": "#/$defs/query",
        "$defs": {key: inputs["$defs"][key] for key in ("expression", "projection", "predicate", "query")},
    }
    files = {}
    for name, schema in (("input", inputs), ("output", outputs), ("query", query)):
        schema = {
            "$comment": LICENSE + " Generated by scripts/generate-mcp-profile.py; do not edit.",
            "$id": f"urn:apache:ossie:execute-query:{name}:{version}",
            **schema,
        }
        files[f"execute-query-{name}.schema.json"] = json.dumps(schema, indent=2) + "\n"
    arguments = next(block for block in blocks if "data_source_id" in block)
    result = next(block for block in blocks if block.get("structuredContent", {}).get("status") == "success")
    error = next(block for block in blocks if block.get("structuredContent", {}).get("status") == "error")
    invalid = {"data_source_id": arguments["data_source_id"], "query": {"measures": ["total_reveneu"]}}
    capture = {
        "$comment": LICENSE + " Generated example capture, not a real engine execution.",
        "protocol_version": "2026-07-28",
        "tool": {"name": "execute_query", "inputSchema": inputs, "outputSchema": outputs},
        "cases": [
            {"name": "example success", "arguments": arguments, "result": result},
            {"name": "example semantic refusal", "arguments": invalid, "result": error},
        ],
    }
    files["example-capture.json"] = json.dumps(capture, indent=2) + "\n"
    return files


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Report drift without writing")
    args = parser.parse_args()
    changed = []
    for name, content in generated_files().items():
        path = DESTINATION / name
        if path.exists() and path.read_text(encoding="utf-8") == content:
            continue
        changed.append(name)
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
    if args.check and changed:
        print("Generated MCP profile files are out of date: " + ", ".join(changed))
        return 1
    print("MCP profile files " + ("updated" if changed else "are in sync"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
