# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

from relationalai.semantics import Date, Decimal, Integer, Model, String, avg, sum

m = Model("model")

Amount = m.Concept("Amount", extends=[Decimal])
EmployeeNr = m.Concept("EmployeeNr", extends=[Integer])
RegisterId = m.Concept("RegisterId", extends=[Integer])
StoreNr = m.Concept("StoreNr", extends=[Integer])
TransactionNr = m.Concept("TransactionNr", extends=[Integer])
UniversalProductCode = m.Concept("UniversalProductCode", extends=[Integer])
ClassNr = m.Concept("ClassNr", extends=[Integer])
CategoryName = m.Concept("CategoryName", extends=[String])
ClassLabelName = m.Concept("ClassLabelName", extends=[String])
RegionName = m.Concept("RegionName", extends=[String])
OrderNr = m.Concept("OrderNr", extends=[Integer])
PaymentId = m.Concept("PaymentId", extends=[Integer])
Employee = m.Concept("Employee")
Contractor = m.Concept("Contractor", extends=[Employee])
PermanentEmployee = m.Concept("PermanentEmployee", extends=[Employee])
Item = m.Concept("Item")
Category = m.Concept("Category")
ClassLabel = m.Concept("ClassLabel")
Class = m.Concept("Class")
Region = m.Concept("Region")
Store = m.Concept("Store")
Terminal = m.Concept("Terminal")
Transaction = m.Concept("Transaction")
Order = m.Concept("Order")
OrderLineItem = m.Concept("OrderLineItem")
Payment = m.Concept("Payment")
CardPayment = m.Concept("CardPayment", extends=[Payment])
CashPayment = m.Concept("CashPayment", extends=[Payment])
db_schema_employees = m.Table("DB.SCHEMA.EMPLOYEES", schema={'EMPNR': Integer, 'LASTNAME': String, 'FIRSTNAME': String, 'MGR': Integer, 'ADDR': String, 'CITY': String, 'STATE': String, 'ZIP': String})
db_schema_contractors = m.Table("DB.SCHEMA.CONTRACTORS", schema={'EMPNR': Integer, 'HOURLYRATE': Integer})
db_schema_permanent_employees = m.Table("DB.SCHEMA.PERMANENT_EMPLOYEES", schema={'EMPNR': Integer, 'SALARY': Integer})
db_schema_locations = m.Table("DB.SCHEMA.LOCATIONS", schema={'STORENR': Integer, 'MGR': Integer, 'REGION': String, 'ADDR': String, 'CITY': String, 'STATE': String, 'ZIP': String})
db_schema_products = m.Table("DB.SCHEMA.PRODUCTS", schema={'UPC': Integer, 'DESCRIPTION': String, 'CLASSNR': Integer, 'CLASSLABEL': String, 'CATEGORY': String})
db_schema_transactions = m.Table("DB.SCHEMA.TRANSACTIONS", schema={'TXN': Integer, 'SKU': Integer, 'TERMINAL': Integer, 'AMT': String, 'REFUNDYN': String, 'TIMESTAMP': String})
db_schema_terminals = m.Table("DB.SCHEMA.TERMINALS", schema={'ID': Integer, 'STORE': Integer, 'SVCDATE': String})
db_schema_lineitems = m.Table("DB.SCHEMA.LINEITEMS", schema={'QUANTITY': String, 'EXTENDEDPRICE': Decimal, 'DISCOUNT': Decimal, 'TAX': String, 'ORDERNR': Integer, 'LINEITEMNR': Integer, 'UPC': String, 'STATUS': String, 'SHIPMODE': String, 'SHIPDATE': String, 'RECEIPTDATE': String})
db_schema_orders = m.Table("DB.SCHEMA.ORDERS", schema={'NR': Integer, 'STORE': String, 'ORDDATE': Date})
db_schema_payments = m.Table("DB.SCHEMA.PAYMENTS", schema={'ID': Integer, 'ORDERNR': String, 'PAYMENTDATE': String, 'AMOUNT': Decimal, 'TYPE': String, 'CARDNUMBER': String, 'CARDEXPIRY': String, 'CARDHOLDERNAME': String, 'CASHRECEIVED': Decimal})
db_schema_retail_facts = m.Table("DB.SCHEMA.RETAIL_FACTS", schema={'ITEM_NR': Integer, 'STORE_NR': Integer, 'WEEK_NR': Integer, 'SLS': Decimal, 'RETURNS': Decimal})

Employee.nr = m.Property(f"{Employee} is identified by {EmployeeNr}")
Item.upc = m.Property(f"{Item} is identified by {UniversalProductCode}")
Category.name = m.Property(f"{Category} is identified by {CategoryName}")
ClassLabel.name = m.Property(f"{ClassLabel} is identified by {ClassLabelName}")
Class.nr = m.Property(f"{Class} is identified by {ClassNr}")
Region.name = m.Property(f"{Region} is identified by {RegionName}")
Store.nr = m.Property(f"{Store} is identified by {StoreNr}")
Terminal.id = m.Property(f"{Terminal} is identified by {RegisterId}")
Transaction.nr = m.Property(f"{Transaction} is identified by {TransactionNr}")
Order.nr = m.Property(f"{Order} is identified by {OrderNr}")
OrderLineItem.order = m.Property(f"{OrderLineItem} belongs to {Order}")
OrderLineItem.nr = m.Property(f"{OrderLineItem} has line item number {Integer}")
Payment.id = m.Property(f"{Payment} is identified by {PaymentId}")
Employee.reportsTo = m.Property(f"{Employee} reports to {Employee:mgr}")
Employee.firstName = m.Property(f"{Employee} {String}")
Employee.lastName = m.Property(f"{Employee} {String}")
Contractor.hourlyRate = m.Property(f"{Contractor} is paid hourly {Integer}")
PermanentEmployee.salary = m.Property(f"{PermanentEmployee} has monthly salary {Integer}")
Item.description = m.Property(f"{Item} {String}")
Item.itemToClass = m.Property(f"{Item} is grouped by {Class}")
Item.weekly_sales = m.Property(f"{Item} sold at {Store} in week {Integer} for {Decimal}")
Item.weekly_gross_sales = m.Property(f"{Item} sold at {Store} in week {Integer} for gross {Decimal}")
Item.weekly_gross_returns = m.Property(f"{Item} returned at {Store} in week {Integer} for {Decimal}")
Item.weekly_net_revenue = m.Property(f"{Item} sold at {Store} in week {Integer} for net {Decimal}")
Item.item_store_sales = m.Property(f"{Item} sold at {Store} for total {Decimal}")
Class.classToCategory = m.Property(f"{Class} is part of {Category}")
Class.classToLabel = m.Property(f"{Class} has {ClassLabel}")
Store.storeToManager = m.Property(f"{Store} is managed by {Employee}")
Store.storeToRegion = m.Property(f"{Store} belongs to {Region}")
Store.avgReturns = m.Property(f"{Store} reports returns of {Item} for average {Amount:amt}")
Store.avgReturnsWithMarkup = m.Property(f"{Store} reports returns of {Item} for 10%-marked-up average {Amount:amt}")
Terminal.deployedTo = m.Property(f"{Terminal} is deployed to {Store}")
Transaction.registeredBy = m.Property(f"{Transaction} is registered by {Terminal}")
Transaction.returns = m.Property(f"{Transaction} refunds {Item} for {Amount}")
Transaction.sales = m.Property(f"{Transaction} sells {Item} for {Amount}")
Transaction.transactionTerminalStore = m.Relationship(f"{Transaction} registered at {Terminal} deployed to {Store}")
Transaction.storeNrViaBinaryChain = m.Property(f"{Transaction} was registered at a terminal deployed to store {StoreNr:store_nr}")
Transaction.storeNrViaTernaryChain = m.Property(f"{Transaction} occurred at store {StoreNr:store_nr}")
Transaction.transactionRegion = m.Property(f"{Transaction} occurred in {Region}")
Transaction.transactionStoreManager = m.Property(f"{Transaction} associated with store manager {Employee}")
Order.orderDate = m.Property(f"{Order} has {Date}")
OrderLineItem.lineitem_extended_price = m.Property(f"{OrderLineItem} has extended price {Decimal:lineitem_extended_price}")
OrderLineItem.lineitem_discount = m.Property(f"{OrderLineItem} has discount factor {Decimal:lineitem_discount}")
OrderLineItem.net_revenue = m.Property(f"{OrderLineItem} has net revenue {Decimal:net_revenue}")
OrderLineItem.discounted_amount = m.Property(f"{OrderLineItem} has discounted amount {Amount:discounted_amount}")
Payment.type = m.Property(f"{Payment} {String}")
Payment.amount = m.Property(f"{Payment} {Decimal}")
CardPayment.cardNumber = m.Property(f"{CardPayment} {String}")
CardPayment.cardHolderName = m.Property(f"{CardPayment} {String}")
CashPayment.cashReceived = m.Property(f"{CashPayment} {Decimal}")
CashPayment.change = m.Property(f"{CashPayment} {Decimal}")

Employee.identify_by(Employee.nr)
Item.identify_by(Item.upc)
Category.identify_by(Category.name)
ClassLabel.identify_by(ClassLabel.name)
Class.identify_by(Class.nr)
Region.identify_by(Region.name)
Store.identify_by(Store.nr)
Terminal.identify_by(Terminal.id)
Transaction.identify_by(Transaction.nr)
Order.identify_by(Order.nr)
OrderLineItem.identify_by(OrderLineItem.order)
OrderLineItem.identify_by(OrderLineItem.nr)
Payment.identify_by(Payment.id)
m.define(Employee.new(nr=db_schema_employees.EMPNR))
m.where(employee := Employee.to_identity(nr=db_schema_employees.EMPNR, unsafe=True), employee_2 := Employee.lookup(nr=db_schema_employees.MGR)).define(employee.reportsTo(employee_2))
m.where(employee := Employee.to_identity(nr=db_schema_employees.EMPNR, unsafe=True)).define(employee.firstName(db_schema_employees.FIRSTNAME))
m.where(employee := Employee.to_identity(nr=db_schema_employees.EMPNR, unsafe=True)).define(employee.lastName(db_schema_employees.LASTNAME))
m.where(contractor := Contractor.lookup(nr=db_schema_contractors.EMPNR)).define(contractor.hourlyRate(db_schema_contractors.HOURLYRATE))
m.where(permanentemployee := PermanentEmployee.lookup(nr=db_schema_permanent_employees.EMPNR)).define(permanentemployee.salary(db_schema_permanent_employees.SALARY))
m.define(Item.new(upc=db_schema_products.UPC))
m.where(item := Item.to_identity(upc=db_schema_products.UPC, unsafe=True), class_ := Class.lookup(nr=db_schema_products.CLASSNR)).define(item.itemToClass(class_))
m.where(item := Item.to_identity(upc=db_schema_products.UPC, unsafe=True)).define(item.description(db_schema_products.DESCRIPTION))
m.define(Item.new(upc=db_schema_retail_facts.ITEM_NR))
m.where(item := Item.to_identity(upc=db_schema_retail_facts.ITEM_NR, unsafe=True), store := Store.lookup(nr=db_schema_retail_facts.STORE_NR)).define(item.weekly_sales(store, db_schema_retail_facts.WEEK_NR, db_schema_retail_facts.SLS))
m.where(item := Item.to_identity(upc=db_schema_retail_facts.ITEM_NR, unsafe=True), store := Store.lookup(nr=db_schema_retail_facts.STORE_NR)).define(item.weekly_gross_sales(store, db_schema_retail_facts.WEEK_NR, (db_schema_retail_facts.SLS + db_schema_retail_facts.RETURNS)))
m.where(item := Item.to_identity(upc=db_schema_retail_facts.ITEM_NR, unsafe=True), store := Store.lookup(nr=db_schema_retail_facts.STORE_NR)).define(item.weekly_gross_returns(store, db_schema_retail_facts.WEEK_NR, db_schema_retail_facts.RETURNS))
m.where(item := Item.to_identity(upc=db_schema_retail_facts.ITEM_NR, unsafe=True), store := Store.lookup(nr=db_schema_retail_facts.STORE_NR)).define(item.weekly_net_revenue(store, db_schema_retail_facts.WEEK_NR, (((db_schema_retail_facts.SLS * 0.9) - (db_schema_retail_facts.RETURNS * 1.1)) + 100)))
m.where(item := Item.to_identity(upc=db_schema_retail_facts.ITEM_NR, unsafe=True), store := Store.lookup(nr=db_schema_retail_facts.STORE_NR), result := sum(db_schema_retail_facts.SLS).per(db_schema_retail_facts.ITEM_NR, db_schema_retail_facts.STORE_NR).where(db_schema_retail_facts.SLS > 0)).define(item.item_store_sales(store, result))
m.define(Category.new(name=db_schema_products.CATEGORY))
m.define(ClassLabel.new(name=db_schema_products.CLASSLABEL))
m.define(Class.new(nr=db_schema_products.CLASSNR))
m.where(class_ := Class.to_identity(nr=db_schema_products.CLASSNR, unsafe=True), category := Category.lookup(name=db_schema_products.CATEGORY)).define(class_.classToCategory(category))
m.where(class_ := Class.to_identity(nr=db_schema_products.CLASSNR, unsafe=True), classlabel := ClassLabel.lookup(name=db_schema_products.CLASSLABEL)).define(class_.classToLabel(classlabel))
m.define(Region.new(name=db_schema_locations.REGION))
m.define(Store.new(nr=db_schema_locations.STORENR))
m.where(store := Store.to_identity(nr=db_schema_locations.STORENR, unsafe=True), employee := Employee.lookup(nr=db_schema_locations.MGR)).define(store.storeToManager(employee))
m.where(store := Store.to_identity(nr=db_schema_locations.STORENR, unsafe=True), region := Region.lookup(name=db_schema_locations.REGION)).define(store.storeToRegion(region))
m.define(Terminal.new(id=db_schema_terminals.ID))
m.where(terminal := Terminal.to_identity(id=db_schema_terminals.ID, unsafe=True), store := Store.lookup(nr=db_schema_terminals.STORE)).define(terminal.deployedTo(store))
m.define(Transaction.new(nr=db_schema_transactions.TXN))
m.where(transaction := Transaction.to_identity(nr=db_schema_transactions.TXN, unsafe=True), terminal := Terminal.lookup(id=db_schema_transactions.TERMINAL)).define(transaction.registeredBy(terminal))
m.where(transaction := Transaction.to_identity(nr=db_schema_transactions.TXN, unsafe=True), item := Item.lookup(upc=db_schema_transactions.SKU), db_schema_transactions.REFUNDYN == "Y").define(transaction.returns(item, Amount(db_schema_transactions.AMT)))
m.where(transaction := Transaction.to_identity(nr=db_schema_transactions.TXN, unsafe=True), item := Item.lookup(upc=db_schema_transactions.SKU), m.not_(db_schema_transactions.REFUNDYN == "Y")).define(transaction.sales(item, Amount(db_schema_transactions.AMT)))
m.define(Order.new(nr=db_schema_orders.NR))
m.where(order := Order.to_identity(nr=db_schema_orders.NR, unsafe=True)).define(order.orderDate(db_schema_orders.ORDDATE))
m.where(order := Order.lookup(nr=db_schema_lineitems.ORDERNR)).define(OrderLineItem.new(order=order, nr=db_schema_lineitems.LINEITEMNR))
m.where(orderlineitem := OrderLineItem.to_identity(order=order, nr=db_schema_lineitems.LINEITEMNR, unsafe=True), order := Order.lookup(nr=db_schema_lineitems.ORDERNR)).define(orderlineitem.lineitem_extended_price(db_schema_lineitems.EXTENDEDPRICE))
m.where(orderlineitem := OrderLineItem.to_identity(order=order, nr=db_schema_lineitems.LINEITEMNR, unsafe=True), order := Order.lookup(nr=db_schema_lineitems.ORDERNR)).define(orderlineitem.lineitem_discount(db_schema_lineitems.DISCOUNT))
m.define(Payment.new(id=db_schema_payments.ID))
m.where(payment := Payment.to_identity(id=db_schema_payments.ID, unsafe=True)).define(payment.type(db_schema_payments.TYPE))
m.where(payment := Payment.to_identity(id=db_schema_payments.ID, unsafe=True)).define(payment.amount(db_schema_payments.AMOUNT))
m.where(cardpayment := CardPayment.lookup(id=db_schema_payments.ID), db_schema_payments.TYPE == "card").define(cardpayment.cardNumber(db_schema_payments.CARDNUMBER))
m.where(cardpayment := CardPayment.lookup(id=db_schema_payments.ID), db_schema_payments.TYPE == "card").define(cardpayment.cardHolderName(db_schema_payments.CARDHOLDERNAME))
m.where(cashpayment := CashPayment.lookup(id=db_schema_payments.ID), db_schema_payments.TYPE == "cash").define(cashpayment.cashReceived(db_schema_payments.CASHRECEIVED))
m.where(cashpayment := CashPayment.lookup(id=db_schema_payments.ID), db_schema_payments.TYPE == "cash").define(cashpayment.change((db_schema_payments.CASHRECEIVED - db_schema_payments.AMOUNT)))
m.where(Payment, Payment.type == "cash").define(CashPayment(Payment))
m.where(Payment, Payment.type == "card").define(CardPayment(Payment))
m.where(amt := Amount.ref(), Item, Store, amt == avg(Amount).per(Item, Store).where(Transaction, Terminal, Transaction.registeredBy(Terminal), Transaction.returns(Item, Amount), Terminal.deployedTo(Store))).define(Store.avgReturns(Item, amt))
m.where(amt_2 := Amount.ref(), Item, Store, amt_2 == Amount((avg(Amount).per(Item, Store).where(Transaction, Terminal, Transaction.registeredBy(Terminal), Transaction.returns(Item, Amount), Terminal.deployedTo(Store)) * 1.1))).define(Store.avgReturnsWithMarkup(Item, amt_2))
m.where(Transaction, Terminal, Transaction.registeredBy(Terminal), Store, Terminal.deployedTo(Store)).define(Transaction.transactionTerminalStore(Terminal, Store))
m.where(store_nr := StoreNr.ref(), Transaction, Terminal, Transaction.registeredBy(Terminal), store_nr == Terminal.deployedTo.nr).define(Transaction.storeNrViaBinaryChain(store_nr))
m.where(store_nr_2 := StoreNr.ref(), Transaction, Terminal, Transaction.transactionTerminalStore(Terminal, Store), store_nr_2 == Store.nr).define(Transaction.storeNrViaTernaryChain(store_nr_2))
m.where(Transaction, Terminal, Transaction.registeredBy(Terminal), Store, Terminal.deployedTo(Store), Region, Store.storeToRegion(Region)).define(Transaction.transactionRegion(Region))
m.where(Transaction, Terminal, Transaction.registeredBy(Terminal), Store, Terminal.deployedTo(Store), Employee, Store.storeToManager(Employee)).define(Transaction.transactionStoreManager(Employee))
m.where(extended_price := Decimal.ref(), discount := Decimal.ref(), net_revenue := Decimal.ref(), OrderLineItem, extended_price == OrderLineItem.lineitem_extended_price, discount == OrderLineItem.lineitem_discount, net_revenue == (extended_price * (1 - discount))).define(OrderLineItem.net_revenue(net_revenue))
m.where(OrderLineItem, OrderLineItem.lineitem_extended_price, OrderLineItem.lineitem_discount, Amount == Amount((OrderLineItem.lineitem_extended_price - OrderLineItem.lineitem_discount))).define(OrderLineItem.discounted_amount(Amount))
